/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as MoreRouteImport } from './routes/more'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsFormRouteImport } from './routes/transactions/form'
import { Route as ChaptersFormRouteImport } from './routes/chapters/form'
import { Route as CategoriesFormRouteImport } from './routes/categories/form'
import { Route as AccountsFormRouteImport } from './routes/accounts/form'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsFormRoute = TransactionsFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => TransactionsRoute,
} as any)
const ChaptersFormRoute = ChaptersFormRouteImport.update({
  id: '/chapters/form',
  path: '/chapters/form',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesFormRoute = CategoriesFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => CategoriesRoute,
} as any)
const AccountsFormRoute = AccountsFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/charts': typeof ChartsRoute
  '/groups': typeof GroupsRoute
  '/more': typeof MoreRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/accounts/form': typeof AccountsFormRoute
  '/categories/form': typeof CategoriesFormRoute
  '/chapters/form': typeof ChaptersFormRoute
  '/transactions/form': typeof TransactionsFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/charts': typeof ChartsRoute
  '/groups': typeof GroupsRoute
  '/more': typeof MoreRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/accounts/form': typeof AccountsFormRoute
  '/categories/form': typeof CategoriesFormRoute
  '/chapters/form': typeof ChaptersFormRoute
  '/transactions/form': typeof TransactionsFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/charts': typeof ChartsRoute
  '/groups': typeof GroupsRoute
  '/more': typeof MoreRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/accounts/form': typeof AccountsFormRoute
  '/categories/form': typeof CategoriesFormRoute
  '/chapters/form': typeof ChaptersFormRoute
  '/transactions/form': typeof TransactionsFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/charts'
    | '/groups'
    | '/more'
    | '/transactions'
    | '/accounts/form'
    | '/categories/form'
    | '/chapters/form'
    | '/transactions/form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/charts'
    | '/groups'
    | '/more'
    | '/transactions'
    | '/accounts/form'
    | '/categories/form'
    | '/chapters/form'
    | '/transactions/form'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/charts'
    | '/groups'
    | '/more'
    | '/transactions'
    | '/accounts/form'
    | '/categories/form'
    | '/chapters/form'
    | '/transactions/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  BudgetRoute: typeof BudgetRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ChartsRoute: typeof ChartsRoute
  GroupsRoute: typeof GroupsRoute
  MoreRoute: typeof MoreRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  ChaptersFormRoute: typeof ChaptersFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/form': {
      id: '/transactions/form'
      path: '/form'
      fullPath: '/transactions/form'
      preLoaderRoute: typeof TransactionsFormRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/chapters/form': {
      id: '/chapters/form'
      path: '/chapters/form'
      fullPath: '/chapters/form'
      preLoaderRoute: typeof ChaptersFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/form': {
      id: '/categories/form'
      path: '/form'
      fullPath: '/categories/form'
      preLoaderRoute: typeof CategoriesFormRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/accounts/form': {
      id: '/accounts/form'
      path: '/form'
      fullPath: '/accounts/form'
      preLoaderRoute: typeof AccountsFormRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsFormRoute: typeof AccountsFormRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsFormRoute: AccountsFormRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesFormRoute: typeof CategoriesFormRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesFormRoute: CategoriesFormRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsFormRoute: typeof TransactionsFormRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsFormRoute: TransactionsFormRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  BudgetRoute: BudgetRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ChartsRoute: ChartsRoute,
  GroupsRoute: GroupsRoute,
  MoreRoute: MoreRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  ChaptersFormRoute: ChaptersFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
